### ISSUE TITLE
Adjust regex to match `nth-*` pseudo-class element strings

### ISSUE THREAD

**Issue by felixhaeberle** [styled-components/vscode-styled-components#283]
**Describe the bug**
As the title described, it would be nice if the regex could also catch the strings provided in strings in pseudo classes.
Such as `nth-child()`, `:nth-last-child()`, `:nth-of-type()`, `:nth-last-of-type()`. 
At the moment, the string doesn't get recognized properly as in normal CSS.

```css
const Listing = styled.div`
  margin-top: calc(var(--rowGap)*1.5);

  div:nth-last-of-type(2n) {
    margin: 0 auto;
  }

  ${media.lessThan('medium')`
    r-grid {
      grid-row-gap: calc(var(--rowGap) / 2);

      r-cell:nth-child(2n+1) {
        margin-bottom: calc(var(--rowGap) / 2);
      }
    }
  `}
`
```

**Screenshot**
![Bildschirmfoto 2021-05-01 um 14 22 46](https://user-images.githubusercontent.com/34959078/116782477-a75c0800-aa89-11eb-87ab-d85ac4214645.png)

**To Reproduce**
```css
const Listing = styled.div`
  margin-top: calc(var(--rowGap)*1.5);

  div:nth-last-of-type(2n) {
    margin: 0 auto;
  }

  ${media.lessThan('medium')`
    r-grid {
      grid-row-gap: calc(var(--rowGap) / 2);

      r-cell:nth-child(2n+1) {
        margin-bottom: calc(var(--rowGap) / 2);
      }
    }
  `}
`
```

**Expected behavior**
The string in the pseudo class function should highlight in one color, at the moment only the first number is highlighted.

**Build environment:**

- OS: MacOS Catalina 10.15.7
- VSCode Version: 1.55.2
- Extension Version: v1.5.2
