### ISSUE TITLE
Multiple Errors generated for one position in code

### ISSUE THREAD

**Issue by ryuujo1573** [styled-components/vscode-styled-components#382]
**Describe the bug (including copyable syntax)**

<img width="532" alt="image" src="https://user-images.githubusercontent.com/16525512/195987937-a1afb3c0-e58d-4a91-af79-1231d844b144.png">

```css
&>*:hover::after {
    counter-reset: score var(--score) scoreMax var(--score-max);
    content: counter(score)" / "counter(scoreMax);
    opacity: 1;
}
```

also, the `@property --var` syntax is marked with warning:
> Unknown at-rule @property. `ts-styled-plugin(9999)`

- OS: macOS Monterey 12.5.1 (Darwin 21.6.0), ssh-remote: Ubuntu 20.04 LTS
- VSCode Version: 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075) arm64
- Extension Version v1.7.5
